#
# build.yml - The Main Build Orchestrator
#
name: Build, Commit, and Release FFmpeg WASM Core

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # --- Phase -1: Install Dependencies ---
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

  # --- Phase 0: Pre-Build Checks ---
  pre-build-checks:
    name: 0. Pre-Build Checks
    needs: install-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Run Linter on Safe Packages
        run: npm run lint --workspace=@ffmpeg/util

  # --- Phase 1: Build Binaries (Parallel) ---
  build-wasm-st:
    name: 1a. Build WASM Core (ST)
    needs: pre-build-checks
    uses: ./.github/workflows/reusable-build-wasm.yml
    with:
      target: build-st
      cache_suffix: st
      artifact_name: core-st-pkg
      artifact_path: packages/core

  build-wasm-mt:
    name: 1b. Build WASM Core (MT)
    needs: pre-build-checks
    uses: ./.github/workflows/reusable-build-wasm.yml
    with:
      target: build-mt
      cache_suffix: mt
      artifact_name: core-mt-pkg
      artifact_path: packages/core-mt

  # --- Phase 2: Build JS Wrappers (Parallel) ---
  build-util-esm:
    name: 2a. Build util (ESM)
    needs: pre-build-checks
    uses: ./.github/workflows/reusable-build-js.yml
    with:
      package_name: util
      format: esm
      needs_wasm: false
      artifact_name: util-esm-dist

  build-util-umd:
    name: 2b. Build util (UMD)
    needs: pre-build-checks
    uses: ./.github/workflows/reusable-build-js.yml
    with:
      package_name: util
      format: umd
      needs_wasm: false
      artifact_name: util-umd-dist

  build-ffmpeg-esm:
    name: 2c. Build ffmpeg (ESM)
    needs:
      - build-wasm-st
      - build-util-esm
      - build-util-umd
    uses: ./.github/workflows/reusable-build-js.yml
    with:
      package_name: ffmpeg
      format: esm
      needs_wasm: true
      wasm_artifact_name: core-st-pkg
      artifact_name: ffmpeg-esm-dist

  build-ffmpeg-umd:
    name: 2d. Build ffmpeg (UMD)
    needs:
      - build-wasm-st
      - build-util-esm
      - build-util-umd
    uses: ./.github/workflows/reusable-build-js.yml
    with:
      package_name: ffmpeg
      format: umd
      needs_wasm: true
      wasm_artifact_name: core-st-pkg
      artifact_name: ffmpeg-umd-dist

  # --- The rest of the file remains the same...