name: Build and Commit FFmpeg WASM Core

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-wasm-st:
    name: 1. Build Single-Threaded WASM Core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-st-${{ hashFiles('**/Dockerfile', '**/Makefile', 'build/**.sh') }}
          restore-keys: |
            ${{ runner.os }}-ccache-st-
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-st
          key: ${{ runner.os }}-buildx-st-${{ hashFiles('**/Dockerfile', '**/Makefile', 'build/**.sh') }}
          restore-keys: |
            ${{ runner.os }}-buildx-st-
      - name: Build Single-Thread (ST) Core
        run: make -j build-st EXTRA_ARGS="--cache-from=type=local,src=/tmp/.buildx-cache-st --cache-to=type=local,dest=/tmp/.buildx-cache-st,mode=max"
      - name: Upload ST Core Artifact
        uses: actions/upload-artifact@v4
        with:
          name: core-st-pkg
          path: packages/core

  build-wasm-mt:
    name: 2. Build Multi-Threaded WASM Core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-mt-${{ hashFiles('**/Dockerfile', '**/Makefile', 'build/**.sh') }}
          restore-keys: |
            ${{ runner.os }}-ccache-mt-
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-mt
          key: ${{ runner.os }}-buildx-mt-${{ hashFiles('**/Dockerfile', '**/Makefile', 'build/**.sh') }}
          restore-keys: |
            ${{ runner.os }}-buildx-mt-
      - name: Build Multi-Thread (MT) Core
        run: make -j build-mt EXTRA_ARGS="--cache-from=type=local,src=/tmp/.buildx-cache-mt --cache-to=type=local,dest=/tmp/.buildx-cache-mt,mode=max"
      - name: Upload MT Core Artifact
        uses: actions/upload-artifact@v4
        with:
          name: core-mt-pkg
          path: packages/core-mt

  build-js:
    name: 3. Build JavaScript Packages
    runs-on: ubuntu-latest
    needs: build-wasm-st # This job depends on the single-threaded core
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download ST Core Artifact
        uses: actions/download-artifact@v4
        with:
          name: core-st-pkg
          path: packages/core
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install JS Dependencies
        run: npm install
      - name: Build JS Packages
        run: npm run build
      - name: Upload JS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: js-pkgs
          path: |
            packages/ffmpeg
            packages/util

  package-and-commit:
    name: 4. Package and Commit All Builds
    runs-on: ubuntu-latest
    needs: [build-wasm-mt, build-js] # This final job depends on both the MT core and the JS packages
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: Make Scripts Executable
        run: chmod +x scripts/*.sh

      - name: Generate Build Receipt
        run: ./scripts/create_build_receipt.sh

      - name: Organize Build Artifacts
        run: ./scripts/organize_builds.sh

      - name: Commit and Push Builds
        run: ./scripts/commit_builds.sh