#
# reusable-build-wasm.yml - Reusable Workflow to Build WASM Core
#
name: Reusable Build WASM Core

on:
  workflow_call:
    inputs:
      # REMOVED: The 'target' input which was causing the semantic error.
      cache_suffix:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string
      # ADDED: Inputs for Docker build arguments to control ST/MT builds.
      ffmpeg_st:
        required: false
        type: string
      ffmpeg_mt:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build WASM Core with Native GHA Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          # FIX: Hardcode the 'target' to the correct Dockerfile stage name.
          target: ffmpeg-wasm-builder
          # FIX: Pass build arguments to the Dockerfile.
          build-args: |
            FFMPEG_ST=${{ inputs.ffmpeg_st }}
            FFMPEG_MT=${{ inputs.ffmpeg_mt }}
          outputs: type=local,dest=${{ github.workspace }}/${{ inputs.artifact_path }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Build Receipt
        run: |
          chmod +x scripts/create_build_receipt.sh
          ./scripts/create_build_receipt.sh ${{ inputs.artifact_path }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}