name: Reusable Build WASM Core

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      cache_suffix:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # This step creates the modern builder and gives it an ID ("buildx")
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-${{ inputs.cache_suffix }}
          key: ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-${{ github.ref_name }}-
            ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-

      # This step passes the builder's name to the script's environment
      - name: Run Build Script
        env:
          BUILDX_BUILDER: ${{ steps.buildx.outputs.name }}
        run: |
          chmod +x scripts/*.sh
          ./scripts/build-wasm.sh ${{ inputs.target }} ${{ inputs.cache_suffix }}

      - name: Create Build Receipt
        run: |
          chmod +x scripts/create_build_receipt.sh
          ./scripts/create_build_receipt.sh ${{ inputs.artifact_path }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}