#
# reusable-build-wasm.yml - Reusable Workflow to Build WASM Core
#
name: Reusable Build WASM Core

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      cache_suffix:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: "DIAGNOSTIC: Show Docker info before setup"
        run: |
          echo "--- Initial Docker/Buildx Version ---"
          docker --version
          docker buildx version
          echo "--- Initial Builders List ---"
          docker buildx ls

      #
      # FIX: Set up QEMU and Docker Buildx to use modern Docker features.
      # This is the most important step. It installs a new builder instance
      # that understands modern commands like "--mount".
      #
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: "DIAGNOSTIC: Show Docker info after setup"
        run: |
          echo "--- Upgraded Docker/Buildx Version ---"
          docker --version
          docker buildx version
          echo "--- Final Builders List (should show a new 'docker-container' builder) ---"
          docker buildx ls

      # This cache is for the Docker layers themselves, to speed up rebuilds.
      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-${{ inputs.cache_suffix }}
          key: ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-${{ github.ref_name }}-
            ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-

      - name: Run Build Script
        run: |
          chmod +x scripts/*.sh
          ./scripts/build-wasm.sh ${{ inputs.target }} ${{ inputs.cache_suffix }}

      - name: Create Build Receipt
        run: |
          chmod +x scripts/create_build_receipt.sh
          ./scripts/create_build_receipt.sh ${{ inputs.artifact_path }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}