#
# reusable-build-wasm.yml
#
name: Reusable WASM Core Build

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      cache_suffix:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.artifact_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Create ccache Directory
        run: mkdir -p .ccache

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ inputs.cache_suffix }}-${{ hashFiles('**/Dockerfile', '**/Makefile', 'build/**.sh') }}
          restore-keys: |
            ${{ runner.os }}-ccache-${{ inputs.cache_suffix }}-

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker Layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-${{ inputs.cache_suffix }}
          key: ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-${{ hashFiles('**/Dockerfile', '**/Makefile', 'build/**.sh') }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ inputs.cache_suffix }}-

      # --- The New Approach ---
      # Execute the build via the wrapper script to handle argument passing correctly.
      - name: Build WASM Core
        run: |
          chmod +x scripts/build-wasm.sh
          ./scripts/build-wasm.sh ${{ inputs.target }} ${{ inputs.cache_suffix }}

      - name: Upload WASM Core Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            ${{ inputs.artifact_path }}
            build/