#
# reusable-build-wasm.yml - Reusable Workflow to Build WASM Core
#
name: Reusable Build WASM Core

on:
  workflow_call:
    inputs:
      cache_suffix:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string
      ffmpeg_st:
        required: false
        type: string
      ffmpeg_mt:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build WASM Core with Native GHA Cache
        uses: docker/build-push-action@v5
        with:
          context: .
          target: ffmpeg-wasm-builder
          build-args: |
            FFMPEG_ST=${{ inputs.ffmpeg_st }}
            FFMPEG_MT=${{ inputs.ffmpeg_mt }}
          outputs: type=local,dest=${{ github.workspace }}/${{ inputs.artifact_path }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # FIX: Change ownership of the Docker output files to the runner user.
      - name: Fix permissions
        run: sudo chown -R runner:docker ${{ github.workspace }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}