#
# reusable-build-js.yml
#
name: Reusable JS Package Build

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      format:
        required: true
        type: string
      needs_wasm:
        required: true
        type: boolean
      wasm_artifact_name:
        required: false
        type: string
      artifact_name:
        required: true
        type: string

jobs:
  build:
    name: Build ${{ inputs.package_name }}-${{ inputs.format }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download WASM Core Artifact
        if: ${{ inputs.needs_wasm }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.wasm_artifact_name }}
          path: packages/core

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          # REMOVED: cache: 'npm'

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # REMOVED: npm install step

      - name: Make Scripts Executable
        run: chmod +x scripts/*.sh

      - name: Build JS Package Variant
        run: ./scripts/build-js-package.sh ${{ inputs.package_name }} ${{ inputs.format }}

      - name: Upload JS Dist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: packages/${{ inputs.package_name }}/dist/${{ inputs.format }}/